# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aeb40df73181883c3d3a9e6df23f2a7a505080340898bfbc0f4d3f434556be4f488183beb485e4d311a074bbf286cac41986a2547d11c80248863f5f10ae165

test:
  secret_key_base: 36b3c8706fb02e1deaa866de2a0ef80b8e2bd95baeef8bdf8708c3cd2bbea0dd97c6d1215ea255c8fc2494565dc3a178508576820a52ca9aea2dc92bd05302a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
